import { expect, test } from "bun:test"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { Process } from "../../src/util/process"
import { withEmbeddedServerArtifactLock } from "../shared/embedded-server-artifact-lock"

const root = path.join(import.meta.dir, "../..")
const runtimeDir = path.join(root, "dist", "node")
const runtimeEntry = path.join(runtimeDir, "node.js")
const modelsSnapshot = path.join(root, "src", "provider", "models-snapshot.js")
const modelsSnapshotPrefix = "// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = "

function writeCurrentModelsFixture() {
  const snapshotSource = fs.readFileSync(modelsSnapshot, "utf8")
  expect(snapshotSource.startsWith(modelsSnapshotPrefix)).toBe(true)

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pawwork-models-dev-"))
  const fixture = path.join(dir, "api.json")
  fs.writeFileSync(fixture, snapshotSource.slice(modelsSnapshotPrefix.length).trim())
  return { dir, fixture, snapshotSource }
}
const requiredWasmMatchers = [
  (file: string) => /^tree-sitter-[^-]+\.wasm$/.test(file),
  (file: string) => /^tree-sitter-bash-.+\.wasm$/.test(file),
  (file: string) => /^tree-sitter-powershell-.+\.wasm$/.test(file),
]

test("build:embedded-server emits the runtime entrypoint and wasm sidecars", async () => {
  await withEmbeddedServerArtifactLock(async () => {
    const modelsFixture = writeCurrentModelsFixture()
    try {
      await Process.run([process.execPath, "run", "build:embedded-server"], {
        cwd: root,
        env: { MODELS_DEV_API_JSON: modelsFixture.fixture },
      })

      expect(fs.existsSync(runtimeEntry)).toBe(true)
      const files = fs.readdirSync(runtimeDir)

      for (const matches of requiredWasmMatchers) {
        expect(files.some((file) => matches(file))).toBe(true)
      }
      expect(fs.readFileSync(modelsSnapshot, "utf8")).toBe(modelsFixture.snapshotSource)
    } finally {
      fs.rmSync(modelsFixture.dir, { recursive: true, force: true })
    }
  })
}, 120_000)
