import { expect } from "bun:test"
import fs from "node:fs"
import path from "node:path"

const modelsSnapshotPrefix = "// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = "

// On Windows runners with `core.autocrlf` enabled (the default for Git for
// Windows), checked-out source files arrive with CRLF line endings even
// though the prefix above is LF. Normalize once before we compare so the
// fixture stays platform-agnostic; `.gitattributes` pins the snapshot file
// to LF for new checkouts as a belt-and-suspenders companion.
function normalize(source: string): string {
  return source.replace(/\r\n/g, "\n")
}

export function writeCurrentModelsFixture(root: string, dir: string) {
  const modelsSnapshot = path.join(root, "src", "provider", "models-snapshot.js")
  const snapshotSource = normalize(fs.readFileSync(modelsSnapshot, "utf8"))
  expect(snapshotSource.startsWith(modelsSnapshotPrefix)).toBe(true)

  const fixture = path.join(dir, "api.json")
  fs.writeFileSync(fixture, snapshotSource.slice(modelsSnapshotPrefix.length).trim())
  return { fixture, modelsSnapshot, snapshotSource }
}

export function expectModelsSnapshotUnchanged(input: { modelsSnapshot: string; snapshotSource: string }) {
  expect(normalize(fs.readFileSync(input.modelsSnapshot, "utf8"))).toBe(input.snapshotSource)
}
