import { describe, expect, test } from "bun:test"
import { isLikelyWriteCommand } from "../../src/tool/bash-write-heuristic"

const positive = [
  "echo x > foo",
  "cmd &> out",
  "cmd &>> out",
  "cat <> file",
  "echo x >| file",
  "false && echo x > foo",
  "ls ; sed -i 's/x/y/' foo",
  "mv a b",
  "cp a b",
  "rm a",
  "rmdir dir",
  "mkdir out",
  "touch file",
  "ls | tee out.txt",
  "yarn",
  "yarn add foo",
  "yarn run build",
  "npm install",
  "npm i",
  "bun add solid-js",
  "bun i",
  "pnpm add solid-js",
  "pnpm run build",
  "cargo build",
  "cargo add serde",
  "cargo run",
  "cargo install cargo-edit",
  "go build ./...",
  "go install example.com/tool@latest",
  "git checkout feature",
  "git apply patch.diff",
  "git clone https://example.test/repo.git",
  "git fetch origin",
  "git mv a b",
  "git pull --rebase",
  "git revert HEAD",
  "git rm old.ts",
  "patch -p1 < fix.patch",
  "chmod +x script.sh",
  "chown user file",
  "ln -s a b",
  "truncate -s 0 file",
  "dd if=a of=b",
  "install src dest",
  "apply_patch < fix.patch",
  "perl -pi -e 's/a/b/' file",
  "awk -i inplace '{print}' file",
  "pip install foo",
  "uv pip install foo",
  "uv add foo",
  "go get example.com/mod",
  "make build",
  "cmake --build build",
  "python setup.py build",
  "python3 setup.py install",
  "officecli create report.docx",
  "officecli add report.pptx / --type slide",
  "officecli set report.xlsx /Sheet1/A1 --prop value=hello",
  "officecli import report.xlsx /Sheet1 --file data.csv --header",
  "officecli close report.pptx",
  'officecli batch report.docx --commands \'[{"op":"set","path":"/body/p[1]","props":{"text":"Done"}}]\'',
  'officecli batch report.docx --commands \'[{"command":"raw-set","part":"/document","action":"replace","xml":"<w:p/>"}]\'',
  "officecli.exe create report.docx",
  "officecli.exe set report.xlsx /Sheet1/A1 --prop value=hello",
  'officecli.exe batch report.docx --commands \'[{"op":"set","path":"/body/p[1]","props":{"text":"Done"}}]\'',
  'cat ops.json | officecli batch "$FILE"',
  "tsc",
  "tsc -p tsconfig.json",
  "vite build",
  "git add file",
  "git restore file",
  "git clean -fd",
  "env FOO=bar npm install",
  "sudo FOO=bar touch file",
  "Set-Content a.txt x",
  "set-content a.txt x",
  "SET-CONTENT a.txt x",
  "New-Item a.txt",
  "Remove-Item a.txt",
  "Copy-Item a.txt b.txt",
  "Move-Item a.txt b.txt",
  "Out-File -FilePath a.txt",
  "Add-Content a.txt y",
  "Clear-Content a.txt",
  "Rename-Item a.txt b.txt",
  'pwsh -c "Set-Content a.txt x"',
  'powershell -c "Remove-Item a.txt"',
]

const negative = [
  "grep 'a > b' file.txt",
  'echo "use > to redirect"',
  "echo ok 2>&1",
  "cmd >&2",
  "ls",
  "cat foo",
  "grep pattern file",
  "grep rm file",
  "echo cp file",
  "printf 'git add file'",
  'echo "Set-Content"',
  "pwd",
  "git status",
  "git log",
  "git diff",
  "find . -name '*.ts'",
  "echo hi",
  "wc -l foo",
  "Get-Content a.txt",
  "Select-String pattern a.txt",
  "Get-ChildItem",
  "Test-Path a.txt",
  "Get-Item a.txt",
  "bun test",
  "npm test",
  "pnpm test",
  "pip show foo",
  "uv pip freeze",
  "uv pip list",
  "uv pip show foo",
  "uv run pytest",
  "vite --version",
  "tsc --noEmit",
  "officecli --version",
  "officecli help docx",
  "officecli view report.docx outline",
  "officecli get report.docx /body --depth 1",
  "officecli query report.xlsx sheet",
  "officecli validate report.pptx",
  "officecli.exe --version",
  "officecli.exe help docx",
  "officecli.exe view report.docx outline",
  "officecli.exe get report.docx /body --depth 1",
  "officecli.exe query report.xlsx sheet",
  "officecli.exe validate report.pptx",
  "officecli batch readonly.officecli",
  "officecli batch report.xlsx",
  'printf \'[{"command":"set","path":"/Sheet1/A1","props":{"value":"x"}}]\' | officecli batch report.xlsx',
  'printf \'[{"command":"set","path":"/Sheet1/A1","props":{"value":"x|y"}}]\' | officecli batch report.xlsx',
  "cat ops.json | officecli batch report.docx",
  "officecli batch report.pptx < ops.json",
  "officecli batch report.xlsx <<'JSON'",
  'officecli batch report.docx --commands \'[{"op":"get","path":"/body","depth":1}]\'',
  'officecli batch report.docx --commands \'[{"command":"view","mode":"outline"}]\'',
]

describe("isLikelyWriteCommand", () => {
  test.each(positive)("detects write-like command: %s", (command) => {
    expect(isLikelyWriteCommand(command)).toBe(true)
  })

  test.each(negative)("ignores read-only command: %s", (command) => {
    expect(isLikelyWriteCommand(command)).toBe(false)
  })
})
